export const WEB_DESIGN = Object.freeze([
  {
    id: 1,
    title: "Appliance Direct",
    desc: "Landing Page Design",
    image: "appliance.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 2,
    title: "Realtor Empress",
    desc: "Landing Page Design",
    image: "realtor.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 3,
    title: "Productivity app",
    desc: "Mobile App Design",
    image: "busybee.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 4,
    title: "Blockstar",
    desc: "Landing Page Design",
    image: "blockstar.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 5,
    title: "Mobile App Empty States",
    desc: "Mobile App Design Exercise",
    image: "mobileexercise.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 6,
    title: "Live Copier",
    desc: "Landing Page Design",
    image: "livecopier.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 7,
    title: "LeadExcess",
    desc: "Landing Page Design",
    image: "leadexcess.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 8,
    title: "Dewha Product Page",
    desc: "Landing Page Design",
    image: "dewha.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 9,
    title: "Starbugs",
    desc: "Landing Page Design",
    image: "starbugs.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=38-986&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=38%3A986&show-proto-sidebar=1&mode=design",
  },
  {
    id: 10,
    title: "Terra And Ember",
    desc: "Landing Page Design",
    image: "terraAndember.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=61-11239&viewport=556%2C135%2C0.03&t=rYSgdqPdjWpwE3n0-1&scaling=scale-down&starting-point-node-id=61%3A11239&show-proto-sidebar=1&mode=design",
  },
  {
    id: 11,
    title: "Miron Digital",
    desc: "Landing Page Design",
    image: "mirondigital.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=64-9563&viewport=556%2C135%2C0.03&t=rYSgdqPdjWpwE3n0-1&scaling=scale-down&starting-point-node-id=64%3A9563&show-proto-sidebar=1&mode=design",
  },
  {
    id: 12,
    title: "Rebank",
    desc: "Landing Page Design",
    image: "rebank.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=59-1933&viewport=556%2C135%2C0.03&t=rYSgdqPdjWpwE3n0-1&scaling=scale-down&starting-point-node-id=59%3A1933&show-proto-sidebar=1&mode=design",
  },
  {
    id: 13,
    title: "NMS Creative Design",
    desc: "Design & wordpress development: oxygen builder",
    image: "nmsdesign.png",
    link: "http://design.nmscreative.com/",
  },
  {
    id: 14,
    title: "Juicelabs",
    desc: "Landing Page Design",
    image: "juicelabs.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=64-3608&viewport=556%2C135%2C0.03&t=rYSgdqPdjWpwE3n0-1&scaling=scale-down&starting-point-node-id=64%3A3608&show-proto-sidebar=1&mode=design",
  },
  {
    id: 15,
    title: "montrose sar",
    desc: "wordpress development: elementor pro",
    image: "msar.png",
    link: "https://montrosesar.org/",
  },
  {
    id: 16,
    title: "So-cal ponds",
    desc: "wordpress development: oxygen builder",
    image: "socalponds.png",
    link: "https://socalponds.com/",
  },
  {
    id: 17,
    title: "Recozy",
    desc: "Landing Page Design and Development",
    image: "recozy.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=64-9167&viewport=556%2C135%2C0.03&t=rYSgdqPdjWpwE3n0-1&scaling=scale-down&starting-point-node-id=64%3A9167&show-proto-sidebar=1&mode=design",
  },
  {
    id: 18,
    title: "Hypeburger",
    desc: "Landing Page Design and Development",
    image: "hypeburger.png",
    link: "https://hypeburger.vercel.app",
  },
  {
    id: 19,
    title: "Superare",
    desc: "Landing Page Design and Development",
    image: "Hyperare.png",
    link: "https://hyperare.vercel.app/",
  },
  {
    id: 20,
    title: "My Allied Health Academy",
    desc: "Web Application Design",
    image: "MAHA.png",
    link: "http://design.nmscreative.com/my-allied-health-academy/",
  },
  {
    id: 21,
    title: "Happy Wally",
    desc: "Landing Page Design",
    image: "happy-wally.png",
    link: "https://www.figma.com/proto/nm5lmRsdzof13EMS0oYZpy/Web-Design-Prototypes?page-id=0%3A1&type=design&node-id=36-6519&viewport=1149%2C-77%2C0.13&t=e2ckE3shACYMrt12-1&scaling=scale-down&starting-point-node-id=36%3A6519&show-proto-sidebar=1&mode=design",
  },
  {
    id: 22,
    title: "TribeTXT",
    desc: "Web Application Design",
    image: "tribetxt.png",
    link: "http://design.nmscreative.com/tribetxt/",
  },
]);
